### ISSUE TITLE
Uncaught TypeError: _inlineStylePrefixer2.default.process is not a function

### ISSUE THREAD

**Issue by dukedougal** [robinweser/react-layout-components#12]
The error says it all.

The <Box> code includes the following:

```
//processing styles and normalizing flexbox specifications
Prefixer.process(styles)
```

The documentation for inline-style-prefixer describes a different way to use it however.

**Comment by robinweser** [comment]
Hey @dukedougal,

I was too busy to update this package to the latest version, but I will fix it as soon as possible. Hopefully this will happen today. 
I will also ship some new Components and reduce the amount of possible props the `Box` Component has by splitting it in different Components. 

The package has been used with React 0.14+ and will work as expected after fixing the prefixer.

Thanks for reporting!
