### ISSUE TITLE
When trying to use Container component, this error is returned: Uncaught ReferenceError: overflowProps is not defined

### ISSUE THREAD

**Issue by nelson-rivera** [robinweser/react-layout-components#18]
I Import both Box and Container:
<tt>import { Box, Container } from 'react-layout-components';</tt>
Then I try to use it within the render function

```
<Container>
  <Box>
    Open Daily
  </Box>
</Container>
```

And this error shows up in console:
`Uncaught ReferenceError: overflowProps is not defined`

**Comment by robinweser** [comment]
Oh damn, how could I have forgotten this! 
Thanks for mentioning, I will fix this instantly

**Comment by robinweser** [comment]
Fixed by #19
