### ISSUE TITLE
[BUG] props is not defined on shortcut elements

### ISSUE THREAD

**Issue by dbismut** [robinweser/react-layout-components#23]
Hey - Aren't your missing `this.props` instead of `props`?

``` javascript
export default class VBox extends Component {
  render() {
    return <Box {...props} column />
  }
}
```

Also, why not creating pure function components such as:

``` javascript
export default (props) => (<Box {...props} column />);
```

**Comment by robinweser** [comment]
Oh damn, I missed that while transforming them, they've been pure functions before, but that does not play well with hot reloading which was the reason why I used classes again.

If you like you could submit a pull request, else I will do it when I am back home in 3 days :p

**Comment by dbismut** [comment]
Haha true that pure functions don't work well with HMR, I know they're working on it though! However, out of curiosity, would that mean that having a pure function VBox would break HMR for any component using a VBox (even if that component is not a pure function)? I'll do the PR but I won't be able to test it :S
