### ISSUE TITLE
Box doesn't work with react 15.0.0

### ISSUE THREAD

**Issue by dlivas** [robinweser/react-layout-components#27]
Please test with react 15.0.0, it seems that flexbox (Box) does not work. When I switch back to react 0.14.8 Everything is aligned as expected but when I switch to react 15.0.0 nothing aligns or wraps etc...

**Comment by dlivas** [comment]
...for some reason it looks like "display: flex" is removed (or overridden) from the container div when I switch to 15.0.0

**Comment by jaskinn** [comment]
+1

It seems to have something to do with the call to 'prefixAll' in 'Box.jsx'. Commenting that out makes everything work again.

**Comment by dlivas** [comment]
thank you jaskinn, I works for me too without the prefixAll. I also do not need prefixAll because I use Radium for vendor prefixing.
thanks again,

**Comment by robinweser** [comment]
@dlivas So did it actually work with React 14? This lib is yet not tested with 15 as I am busy right now, but I can't see why this should be an issue with React actually. Ill try to test it out soon

**Comment by jaskinn** [comment]
Version 2.2.0 (of react-layout-components) has been working for me with React 0.14.8 (and still is). I am also baffled as to what changes in 15 could be causing this.

**Comment by dlivas** [comment]
Yes, it works with react 14 as always did.
with react 15.0.0 works after I commented out the vendor prefixing. It looks that the problem is in inline-style-prefix-all module when we use 15.x.

I pass Box through radium "Radium(Box)" before I use it, I think that this gives me the vendor-prefixing I need. I will test it  though.

**Comment by skratchdot** [comment]
Same here.  Works w/ React 14, but not React 15 for some reason.

**Comment by robinweser** [comment]
I've just tested the results and styles. This seems to be a bug within React itself as the styles get prefixed as should: e.g. display gets: 
`display: "-webkit-box;display:-moz-box;display:-ms-flexbox;display:-webkit-flex;display:flex"` but the whole property gets somehow removed after mounting to the DOM.

@dlivas Also note that Radiums uses the same prefixer under the hood (at least one of both available prefixer I created). Perhaps this issue might return with Radium as well.

**Comment by skratchdot** [comment]
@rofrischmann - Yes- it even appears your [inline-style-prefixer](https://github.com/rofrischmann/inline-style-prefixer) library is referenced in this ticket: https://github.com/facebook/react/issues/6467 (also seems to affect your [inline-style-prefix-all](https://github.com/rofrischmann/inline-style-prefix-all) library).

**Comment by skratchdot** [comment]
I'm guessing a nasty work around would be including a style tag in the <head /> onComponentDidMount (if it hasn't already been injected).

``` css
<style id="__SOME_ID_NO_ONE_ELSE_WOULD_USE__">
    .___INLINE_STYLES_HACK_DISPLAY_FLEX___ {
        display: -webkit-box;
        display:-moz-box;
        display:-ms-flexbox;
        display:-webkit-flex;
        display:flex
    }
    /* you could add other prefixed styles here (that rely on the inline hack) */
</style>
```

Then in your lib you could use class instead of inline styles for the inline styles that require the hack you were using.

This might be against the philosophy of your lib though (using classes and injecting a style tag).  I'm hoping there's some other way to fix this.

**Comment by robinweser** [comment]
Alright. As I see, React 15 actually "killed" inline styles as they're used up to 0.14 as without alternative values, inline styles are not usable within older browsers that do not support newest specs. I will have to think about something to fix this. Might use a single class to polyfill the `display`. All other props should still do their job as there're no values that need to be prefixed alternatively. 
Thanks for your effort here!

**Comment by skratchdot** [comment]
gearon also has an interesting solution in the 2nd comment on that thread:

> For example you can create a DOM element once when your code initializes, set different values of style.display on it, and see whether it sticks or gets reset. When it sticks, it means the browser supports the given value. This way you can build up a dictionary of mappings between standard values and the ones supported by the browser. Most likely there are some libraries that can do this for you.

**Comment by skratchdot** [comment]
...and thanks for your work on this great lib.  I looked at a few other flex layout libs, and found this one to fit my needs the best.

**Comment by robinweser** [comment]
Oh yeah I know this method actually, but don't think it is a "good" solution. It is not performant to mount all the DOM elements to only get supported properties. I hope I'll find some time this week to "fix" the issues.
Thanks a lot :) Let's make this lib working again as fast as possible.

**Comment by markerikson** [comment]
Anyone had a chance to look at this?  I'd like to try upgrading to React 15 for my project, but this would appear to block that.

**Comment by SteveEisner** [comment]
I'm blocked by this as well.  Really appreciate the hard work on these components, though we may have to switch away if they prevent us from upgrading React :(   Let me know if there's anything we can do to help investigate or fix this issue!

**Comment by jaskinn** [comment]
I completely agree with SteveEisner's comments.

**Comment by robinweser** [comment]
I am right now trying out some stuff, sorry for the late response, but I have been in stress with exams lately. I am just unsure how to add the single CSS class without a mess of extra code, but I guess the best solution right now is to just add a new stylesheet on `componentDidMount` once.

**Comment by SteveEisner** [comment]
Thanks!  And I really did mean it - if there's anything we can do to help test, please let us know.  We don't want to switch, we just need to know that our upgrade path is clear :)  Good luck on your exams.

**Comment by robinweser** [comment]
Again I want to apologize for the delay, I am ill and yet have to go for 2 more exams this week.
I might push something tomorrow or on thursday.

**Comment by markerikson** [comment]
Appreciate the update, and please take care of yourself first :)

**Comment by oallouch** [comment]
Come on, man !
I really need React 0.15 .

**Comment by skratchdot** [comment]
I just fix this in my local repo b/c I'm still in development mode.

(1) In your root project folder, create `fix_flex.sh`:

``` bash
#!/bin/bash
LINE_NO="107"
CHANGE_FILE="./node_modules/react-layout-components/lib/components/Box.js"
CHANGE_LINE=$(sed "${LINE_NO}q;d" "${CHANGE_FILE}")
EXISTING_LINE="      var prefixedStyles = (0, _inlineStylePrefixAll2.default)(styles);"
FIXED_LINE="      var prefixedStyles = styles;"
if [ "${CHANGE_LINE}" == "${EXISTING_LINE}" ]; then
  sed -i.bak "s/${EXISTING_LINE}/${FIXED_LINE}/" "${CHANGE_FILE}"
fi
```

(2) Now run: `chmod +x ./fix_flex.sh`
(3) Now run `./fix_flex.sh`

All that does is change line `107` of `Box.js` to stop using the autoprefixer (which I don't need for development)

**Comment by robinweser** [comment]
@skratchdot Nice hack for development, but yet this does not fix the issue itself as you can't use it if you develop for all major browser (which sometimes need those prefixes).

I will push the update in ~2 hours, but there might be a change soon as React itself might add support for multiple values https://github.com/facebook/react/pull/6701

**Comment by skratchdot** [comment]
Ah, that's great!  Thanks for the update.  I just figured I'd share that snippet, b/c it allowed me to start my React 15 upgrade, while waiting for the next update of this lib.  The code I'm working on won't be released for a while, so my browser support requirements are small at the moment.  It'll be cool if FB supports multiple values again.
To the others reading: don't make the change to line 107 if you are running in production (or need good browser support).  I'm only using it locally because I don't need to support old browsers at the moment!
