### ISSUE TITLE
Add childs dynamicaly to Box and Vbox

### ISSUE THREAD

**Issue by Miteshdv** [robinweser/react-layout-components#29]
How we can dynamicaly add children to these layout components

**Comment by robinweser** [comment]
What do you mean by "dynamically adding children"?

**Comment by Miteshdv** [comment]
Ok, see i have 50 elements that will appear based on codition so i need to add these 50 elements in Vbox . can we acheive this via react-layout-componets ? because i no where see addChild method

**Comment by robinweser** [comment]
Well, that's something you'd do with react in general right?

``` javascript
<VBox>{ yourchildren }</VBox>
```

or am I missing something?

**Comment by Miteshdv** [comment]
ok, thanks !
