### ISSUE TITLE
many warnings because of React 15.2.0

### ISSUE THREAD

**Issue by oallouch** [robinweser/react-layout-components#32]
Hi,

React 15.2.0 send a warning when an unknown property is given to a div (for instance).
see https://facebook.github.io/react/docs/transferring-props.html#transferring-with-...-in-jsx

Could you please install filters ?

thx in advance

Olivier Allouch
www.illicotravel.com

**Comment by robinweser** [comment]
Yeah I know about that issue. For now it would be safe to use 15.1 instead. I am not really able to do much for this repo right now, but feel free to just PR the changes and I'll publish those.

**Comment by oallouch** [comment]
come on, man ! it's only a few lines of code.
Anyway, I understand this kind of things happen, I seriously do.
Maybe you should add a link in your readme telling us this library is no more active and we should move to something like https://github.com/zippyui/react-flex .
Anyway, thx. This library has been useful.

**Comment by robinweser** [comment]
This has been fixed thanks to @mrgenixus
