### ISSUE TITLE
Container - Position attr of 0 does not work

### ISSUE THREAD

**Issue by aap82** [robinweser/react-layout-components#34]
Using a position prop of 0 on the Container component does not work.  It doesn't pass this test:

```
containerProps.forEach(prop => {
  **if (props[prop])** {
    styles[prop] = props[prop]
  }
})
```

**Comment by robinweser** [comment]
Gotcha! Would you want to provide a PR to fix this issue? @aap82

**Comment by aap82** [comment]
I could.  However, I doubt you would want me to.  I literally taught my self javascript a few months ago, have no idea what i'm doing half the time.

**Comment by robinweser** [comment]
Haha. Than its even worth to try it out :) Learning by doing, you know :P 
To give you a hint: `props[prop]` takes the value and mimics a boolean. Therefore any value equals `true` except negative values **(including 0)**, `null` and `undefined`.
So basically when using `position={0}` prop it evaluates to `if (0)` which of course is `false`. Luckily there's the `hasOwnProperty`-method which every objects has. We could replace the `if (props[prop])` with `if (props.hasOwnProperty(prop)` and that's it =)

**Comment by aap82** [comment]
Ok, well this was my first pull request.  Let me know if it's done right.  Thanks.

I've just become accustomed and prefer using coffeescript, which i think is great for noobs like myself.  Because then it would be just 

> if props[prop]? then ...
