### ISSUE TITLE
Page component not being exported properly

### ISSUE THREAD

**Issue by markerikson** [robinweser/react-layout-components#38]
As of commit 2f8d51d2ad , the Page component is no longer being exported.  The change from a class to a functional component left out the `export` keyword.

**Comment by markerikson** [comment]
Can we get a package bump/re-release to include this? Thanks!

**Comment by robinweser** [comment]
Oh ofc. Forgot about that :p
Edit: Done!

**Comment by markerikson** [comment]
Sweet!  Thanks again for an extremely useful library.

**Comment by robinweser** [comment]
You're welcome =)
