### ISSUE TITLE
Fela support?

### ISSUE THREAD

**Issue by johanneslumpe** [robinweser/react-layout-components#40]
How about making the components compatible with fela, vs using pure inline styles?

**Comment by robinweser** [comment]
I am soon releasing something similar but Fela specific. I don't think its a cool idea to make this universal lib just for Fela :P @johanneslumpe

**Comment by johanneslumpe** [comment]
@rofrischmann I didn't say just for fela :P I said to just make it compatible, but that would probably be hard. I guess I'll have to roll my own for now.

**Comment by robinweser** [comment]
I am releasing my own really soon, so don't worry :P just have to finish docs

**Comment by johanneslumpe** [comment]
@rofrischmann Is it going to have the same components as this? If so, it would be easy to switch out my crude copy for the npm module ;)
