### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by zhaoyao91** [robinweser/react-layout-components#42]
It has no updates this year.

**Comment by robinweser** [comment]
It's rather "done". There's nothing I'd add to it and it's fully ready to be used in production as well. Also, there was no PR or any change request.

**Comment by zhaoyao91** [comment]
Thank you. Do you plan to make some similar package for the new CSS grid feature?

**Comment by robinweser** [comment]
I've not planned anything related CSS grid yet. I'm not using it and as well not liking it at all. I get all my stuff done with Flexbox and Grid support is still pretty bad...
But I am sure there're quite a few React components out there to support CSS grid.

**Comment by zhaoyao91** [comment]
3q for your reply 😊
