### ISSUE TITLE
React 15.5+ compatibility 

### ISSUE THREAD

**Issue by beatlecz** [robinweser/react-layout-components#48]
It seems like a there is some problem with PropTypes since React version 15.5 :(

**Comment by robinweser** [comment]
Feel free to send a PR, you just need to add `prop-types` and replace all `import { PropTypes } from 'react'` with `import PropTypes from 'prop-types'.

**Comment by jojolarx** [comment]
Didn't [this](https://github.com/rofrischmann/react-layout-components/pull/46) PR fixed it?
